### ISSUE TITLE
Water - Energy support

### ISSUE THREAD

**Issue by anktababa** [Aohzan/ipx800#41]
Hi, 

First, i am not sure used to HA yet so i might be wrong, if that's the case, sorry :)

I am using IPX800V4 to count the water consumption. Using the GCE Pulse counter, 1 Pulse = 1 Liter
Thanks to your integration, i have in HA the entities (sensor.compteur_eau, type : counter, unit_of_measurement: "L")

I am trying to add Water to the energy tab of HA but it is not possible to use it ;

> "No matching statistics found" 
> 
> Open an issue with the author of the integration and link them to (https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics).

is it something that is possible ?

Thank you.

**Comment by Aohzan** [comment]
Hello
You have to use a template, like
```yaml
---
template:
  - sensor:
      - name: "Compteur eau Total"
        unit_of_measurement: "m³"
        device_class: water
        state_class: total_increasing
        state: "{{ (states('sensor.compteur_eau') | int) / 1000 }}"
        unique_id: compteur_eau_total
```
in my example, I have to divide by 1000
