### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by danamaki** [Aohzan/ipx800#46]
J'ai installé ipx800 sur HA.
J'ai inclu dans le fichier configuration :

````yaml
ipx800v4:
  - name: IPX800_V4  
    host: "192.168.0.43"
    api_key: "motdepasse"
    devices:
      - name: spotpiscine
        icon: mdi:water-boiler
        type: "relay"
        component: "switch"
        id: 3
```

Mais j'ai échec de la configuration après redémarrage...
Pouvez-vous m'aider ?

Merci
