### ISSUE TITLE
Push dimmer value to HA

### ISSUE THREAD

**Issue by Kolia56** [Aohzan/ipx800#51]
**Describe the bug**
Thank you for this integration. It is working very well and speeds up the development process.
I'm not too sure whether it is a bug or something missing in ipx800v4 labels. It seems not possible to push dimmer value to HA, however it possible to send dimmer state (on/off).
There is some side effect when the user switches on and off as this short video shows it. When it is switched on there is a short time when light is set to minimal value then it is set to the last knwon value, when it is switched off, the dimmer value is greyed out and after some time the bar goes to 0

https://github.com/Aohzan/ipx800/assets/20872098/2ff29aca-3fd0-4dd6-8e49-200cd8fbc2dd

**Configuration**
```
ipx800v4:
  - name: IPX800
    host: "xxx.xxx.xxx.xxx"
    api_key: "api_key"
    push_password: aaaaa
    devices:
      # Relays
      - name: Chauffe-eau
        icon: mdi:water-boiler
        type: "relay"
        component: "switch"
        id: 1
      - name: Couloir grenier
        icon: mdi:lightbulb
        type: "relay"
        component: "switch"
        id: 2
      - name: Porte d'entrée
        icon: mdi:outdoor-lamp
        type: "relay"
        component: "switch"
        id: 3
      - name: Lampes buffet
        icon: mdi:lamp
        type: "relay"
        component: "switch"
        id: 4
      - name: Grenier
        icon: mdi:lightbulb
        type: "relay"
        component: "switch"
        id: 5
      # Dimmers
      - name: Suspension entrée
        icon: mdi:ceiling-light
        type: xdimmer
        component: light
        id: 3
      - name: Suspension centrale
        icon: mdi:ceiling-light
        type: xdimmer
        component: light
        id: 4
      - name: Couloir
        icon: mdi:ceiling-light
        type: xdimmer
        component: light
        id: 1
      - name: Portail
        icon: mdi:coach-lamp
        type: xdimmer
        component: light
        id: 2
      # Fils pilote
      - name: Radiateur fenêtre Braii
        icon: mdi:radiator
        type: x4fp
        component: climate
        ext_id: 1
        id: 1
      # Entrées numériques
      # - name: Fond du puisard
      #   icon: mdi:water-minus
      #   component: digitalin
      #   type: binary_sensor
      #   id : 7
      # - name: Seuil haut du puisard
      #   icon: mdi:water-alert-outline
      #   component: digitalin
      #   type: binary_sensor
      #   id: 8
      # Capteur THL
      - name: Cuisine Braii
        icon: mdi:thermometer
        type: xthl
        component: sensor
        id: 1
      - name: Cave
        icon: mdi:thermometer
        type: xthl
        component: sensor
        id: 2
```

**Expected behavior**
Is there a way to push the dimmer value at the same time state is pushed? As a matter of fact, this is not a big deal since I'm not using ipx800v4 interface.
Bar should not be set to 0 after sometime, and dimmer should be set right away to its last value.

Edit: more of a problem. When physical switch is used to switch on or off light, the bar stays at the minimum value, whereas the light is set at the expected value.

**Screenshots**

**Debug logs**
```
not applicable
```
